alias la='"ls" --color=auto --group-directories-first -lAhX'
alias ls='ls --color=auto --group-directories-first --time-style=iso -BhgG'
alias ll='ls -alF'
alias l='ls -CF'
alias dir='ls --color=auto --format=vertical'
alias tree='tree -L 2'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias untar='tar -xvf'
alias mv='mv -i'
alias cp='cp -i'
