set nocompatible
source ~/.vim/altbinds.vim
source ~/.vim/settings.vim
source ~/.vim/autocmds.vim

" Plug
if !empty(glob("~/.vim/autoload/plug.vim"))
    source ~/.vim/plugins.vim
else
    if confirm("Fetch Vim-Plug?","Y\nn") == 1
        execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.github.com/junegunn/vim-plug/master/plug.vim'
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
        source ~/.vim/plugins.vim
    endif
endif
