# Hitting someone
:no_skip
:light red
You hit %s
and %s %s %s.

# Getting hit
:red
%shits you.
are %s%s.
Touching %s paralyzes you!

:light cyan
can move again!

# Killing someone
:yellow
and %s %s.
and %s %s right away!
and transform %s into a %s heap!

# Experience
:light green
[+%lldxp]

# Pick pocketing
:light cyan
%s does not seem to own anything of value.
already have cleaned out %s.
%s does not have any suitable pockets.

:light green
steal %s%s!

:light red
You don't see anyone with pockets to pick.

# Mindcraft
:light cyan
%s resists your mental incursion!
grasp at the mind of %s but %s resists!

:light red
grasp at the mind of %s, wounding %s!

:yellow
grasp at the mind of %s.
grasp at the mind of %s, killing %s!

:red
You sense an undead conscience clawing at your mind!

# Herb messages
:light cyan
Some strong herb bushes are growing here.

:light green
Some herb bushes full of blossoms are growing here.
A new herb bush blossoms.
One herb bush suddenly looks more vigorous.

:red
Some withered herb bushes are growing here.

:red
The herb bush suddenly withers and disappears.

# Miscellaneous
:light cyan
The bleeding stops.
You really hurt your foot kicking the wall!
hear an evil hissing and something large crawling about the ground!
You don't have any appropriate key to use on the door.
You don't have any appropriate key in working order.

# Corruption
:magenta
feel corrupted!

# Detrimental date effects
:red
You feel unlucky.
You feel slightly exhausted today.

# Benefical date effects
:green
You feel that starting your adventure on Creator's Day was a good idea.
A lone star leads you to this remote valley.
You feel well prepared for the coming year.
You feel treated.

# Stat gain
:light green
Your muscles feel stronger.
Your muscles feel stronger!
You suddenly feel stronger!
You feel studious.
You feel studious!
Your will seems inflexible.
Your will seems inflexible!
Your movements are getting swifter.
Your movements are getting swifter!
Your health increases.
Your health increases!
You feel very self-confident.
You feel very self-confident!
Your looks improve.
Your looks improve!
You feel more in touch with the world.
You feel more in touch with the world!
Your senses sharpen.
Your senses sharpen!
feel good about your %s potential.
feel very good about your %s level.
You feel more powerful.

# Skill gain
:light blue
Your '%s' skill increases by %+d
to %d.
improve in the area of '%s' (from %s to
%s).
improve your skill in the shield group to level %d.
improve your skill in the '%s' weapon group to level %d.
improve your skill with the '%s' weapon category to level %d.
become more efficient in using the '%s' spell (now %+d).

# Food rotting
:brown
Your equipment seems to become smelly.
Your equipment suddenly seems to weigh less.
Your %s rots away!
Your %s starts to rot!
Your %s slowly rots away!
notice %s %s rotting away.


# Dungeon features hilight
:yellow
Great treasures are buried here!

# Spell effects
:cyan
You feel your spirits rise!
You feel your spirits soar!
Your eyes itch.
You feel like Atlas himself.
Suddenly everything around you seems to slow down.
Suddenly you can't see yourself!
For a moment you were gone... then your eyes adjust.
Suddenly you can see yourself again!
Your mood darkens.
Your eyesight adjusts to normality once more.

# Spell effects (no skip)
:red
You feel your great strength waning.
Suddenly your extraordinary carrying capacity fails you.
Suddenly everything around you seems to speed up!

# Player accomplishments
:yellow
have just completed your current quest.
Congratulations! You advance to level %d.

# Stat loss
:red
You feel as if this was not a good idea!
Your muscles soften.
Thinking seems to get tougher.
You feel soft-hearted.
You are getting shaky.
It seems that you are getting a cold.
You feel reserved.
You are growing a wart.
You are getting out of touch with everything.
You seem to get less perceptive.
You feel weak!
You feel exhausted!
You suddenly age!

# Equipment damage/destruction
:red
Your %s are destroyed.
Your %s are damaged.
Your %s corrodes!
Your %s corrode!
It is destroyed.
They are destroyed.
They are destored.
Your weapon breaks!
Your %s %s damaged.
Your %s %s destroyed!
Your %s rust%s!
%lld %sof your %s %s!
Your %s %s!
Your %s is finally damaged beyond repair!
The %s on the floor melts down into a puddle of metal!
The %s %s %s!
The %s on the ground %s!
Something on the floor melts down into a puddle of metal!
Something on the ground %s!
The %s %s transformed into a rusty heap!
The %s rust%s!
It is annihilated!
They are annihilated!

# Replaced combat messages
:replace
:light gray
fails to hurt you.|hits your armor.
block %s.|You block.
deflect the attack of %s.|You deflect.

:replace
:red
punches through your armor and|pierces and

# Negative pool effects
:replace
:regex
:red
You taste bitter bile in your mouth.|Lost acid resistance.
You sweat.|Lost fire resistance.
You shiver.|Lost cold resistance.
You feel shocked.|Lost shock resistance.
Your stomach stings painfully.|Lost poison resistance.
You feel cheated.|Lost luck.
You feel very bad off.|Lost fate smile.
Bah! This liquid is extremely filthy!|Got sickness.
You feel steady.|Lost teleportitis.
You suddenly hate the thought of jumping around.|Lost teleport control.
You feel tired.|Lost sleep resistance.
You feel shaken.|Lost stun resistance.
You feel inflexible.|Lost paralyzation and petrification resistance.
You feel gnarly.|Lost petrification resistance.
You feel like an endangered species.|Lost death ray resistance.
Your outfit suddenly looks much cleaner.|Lost invisibility.
You suddenly are visible again.|Lost invisibility.
Your eyes sting for a second.|Lost see invisible.
You suddenly can see yourself.|Lost temporary invisibility.
You sense trouble.|Got cursed.
You start a trip on the road to nowhere.|Got cursed.
You become depressive.|Got doomed.
You feel very very bad.|Got doomed.
You continue the trip on the road to nowhere.|Got doomed.
:no_regex

# Gaining intrinsics
:replace
:regex
:light green
You feel your spirits rise!|Got lucky.
You feel an inner strength lifting your spirits!|Got lucky.
You feel spiritually elated!|Got lucky.
You feel that a sinister curse is lifted from you.|Lost cursed.
You feel a terrible gloom being lifted from you.|Lost doomed.
You feel relieved.|Lost cursed.
You feel elated.|Lost doomed.
You swallow hard.|Got acid resistance.
You feel cool.|Got fire resistance.
You feel hot-headed.|Got cold resistance.
You hear a voice calling you 'Iceberg'|Got shock resistance.
Your digestion calms down.|Got poison resistance.
You feel lucky.|Got lucky.
You feel very lucky.|Got fate smile.
You feel jumpy.|Got teleportitis.
You suddenly feel like jumping around.|Got teleport control.
You feel totally awake.|Got sleep resistance.
You feel very controlled.|Got stun resistance.
You are moved by the sheer pleasure of this sip of fluid.|Got paralyzation resistance.
You feel flexible.|Got petrification resistance.
You feel bold at the thought of danger.|Got death ray resistance.
Suddenly you are gone.|Got temporary invisibility.
You feel translucent.|Got temporary invisibility.
You feel on air.|Got temporary invisibility.
Your eyes tingle for a second.|Got see invisible.
No effect... as far as you notice.|Got invisibility.
You suddenly are gone.|Got invisibility.
You feel dizzy for some seconds.|Got invisibility.
You feel very much in control.|Got teleport control.
You feel ecstatic.|Got shock resistance.
Your stomach tingles.|Got acid resistance.
Your stomach seems to be burning in bright flames.|Got fire resistance.
:no_regex

# Dungeon features
:replace
:cyan
You hear a distant wind.|You hear a vortex!

:replace
:light gray
You notice a slurping sound in the distance.|You hear spiders.
You hear splashing sounds.|You hear a pool splashing.

:replace
:yellow
You hear the steps of the royal guard.|Royal vault.

# Unnecessary messages
:allow_skip
:suppress
Select the companion you want to issue an order to.
Select the slave to command.
Extended drop command.
%s mumbles:
%s tries to disarm you but you foil %s plan due to your %s with your %s.
%s spins a large web!

# Suppressed combat messages
:suppress
%s seems to be confused.
%s misses you.
%s is struggling against a large web holding %s!

# Arena
:suppress
You talk to Dak, the arena master~.
"%s, %s! %s?"
"Ze'll fight'll run till one of ya two is dead. Good luck!"
hear the cries of the crowd: "%s! %s! %s!"
You hear the ecstatic cries of a large crowd!

# ToEF
:suppress
Your equipment is protected from the fire by a thin sheet of ice emanating from your hands.
The air is extremely hot!
searing flames.

# Casino
#At the front of the machine pictures start to spin.
#You %s
#get %s,
#%s
#and %s.
#The machine continues to glow in happy colors.
#Dong!
#You win %lld gold piece%s!
#pull the lever on the right side of the machine.
#
#(easily cutting through %s armor with the %s)
#You lust for blood!
#The %s returns!
#You manage to catch it.
#You fail to catch it.
