:allow_skip

# Hitting someone
:light red
and %s %s %s.

# Getting hit
:red
punches through your armor and
%shits you.
are %s%s.

# Killing someone
#:light cyan
#and %s %s.
#and %s %s right away!
#and transform %s into a %s heap!

# Experience
#:light green
#[+%ldxp]

# Pick pocketing
#:light cyan
#%s does not seem to own anything of value.
#already have cleaned out %s.
:light green
steal %s%s!
[+%ldxp]

# Herb messages
:light green
Some herb bushes full of blossoms are growing here.
:light cyan
Some strong herb bushes are growing here.
:red
Some withered herb bushes are growing here.

# Miscellaneous
:light cyan
The bleeding stops.
You really hurt your foot kicking the wall!
%s does not seem to own anything of value.
already have cleaned out %s.
and %s %s.
and %s %s right away!
and transform %s into a %s heap!

# Corruption
:magenta
feel corrupted!

# Player accomplishments
:no_skip
:yellow
just have completed your current quest.
Congratulations! You advance to level %d.

# Stat gain
:no_skip
:light green
Your muscles feel stronger.
Your muscles feel stronger!
You feel studious.
You feel studious!
Your will seems inflexible.
Your will seems inflexible!
Your movements are getting swifter.
Your movements are getting swifter!
Your health increases.
Your health increases!
You feel very self-confident.
You feel very self-confident!
Your looks improve.
Your looks improve!
You feel more in touch with the world.
You feel more in touch with the world!
Your senses sharpen.
Your senses sharpen!
feel good about your %s potential.
feel very good about your %s level.

# Stat loss
:no_skip
:red
You seem to get less perceptive.
You are getting out of touch with everything.
You are growing a wart.
You feel reserved.
It seems that you are getting a cold.
You are getting shaky.
You feel soft-hearted.
Thinking seems to get tougher.
Your muscles soften.
You feel weak!
You feel exhausted!
You suddenly age!

# Skill gain
:no_skip
:light blue
Your '%s' skill increases by %+d
to %d.
improve in the area of '%s' (from %s to
%s).
improve your skill in the shield group to level %d.
improve your skill in the '%s' weapon group to level %d.
improve your skill with the '%s' weapon category to level %d.
become more efficient in using the '%s' spell (now %+d).

# Equipment damage/destruction
:no_skip
:red
Your %s are destroyed.
Your %s are damaged.
Your %s corrodes!
Your %s corrode!
They are destored.
Your weapon breaks!
Your %s %s damaged.
Your %s %s destroyed!
Your %s rust%s!
%ld %sof your %s %s!
Your %s %s!
Your %s is finally damaged beyond repair!
Something on the floor melts down into a puddle of metal!
Something on the ground %s!
The %s %s transformed into a rusty heap!
The %s rust%s!
They are annihilated!
It is annihilated!

# Food rotting
:no_skip
:brown
Your equipment suddenly seems to weigh less.
Your %s rots away!
Your %s starts to rot!
Your %s slowly rots away!
notice %s %s rotting away.

# Spell effect messages
:no_skip
:cyan
You feel your spirits rise!
You feel your spirits soar!
Your mood darkens.
Your eyes itch.
Your eyesight adjusts to normality once more.
You feel like Atlas himself.
You feel your great strength waning.
Suddenly your extraordinary carrying capacity fails you.
Suddenly everything around you seems to speed up!
Suddenly everything around you seems to slow down.
Suddenly you can't see yourself!
For a moment you were gone... then your eyes adjust.
Suddenly you can see yourself again!

# Unnecessary messages
:suppress
Select the companion you want to issue an order to.
Select the slave to command.
Extended drop command.
#(easily cutting through %s armor with the %s)
#You lust for blood!
#The %s returns!
#You manage to catch it.
#You fail to catch it.
